[package]
name = "waldb-node"
version = "0.1.0"
authors = ["Elkyn"]
edition = "2021"
exclude = ["artifacts.json", "index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "1.1"
serde_json = "1.0"