name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        working-directory: ./bindings/node
        run: npm install
        
      - name: Build
        working-directory: ./bindings/node
        run: npm run build-release
        
      - name: Run tests
        working-directory: ./bindings/node
        run: npm test
        
      - name: Publish to npm
        working-directory: ./bindings/node
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}